Fix iPhone user issues
afnexus/raid-website pull request #35
Opened 2022-12-27 06:54 UTC by MakiseKurisuX

## Description

Removed mapping for images (causing issues with iPhone users) 
Removed most of the css (cannot remove for Solvathon as the font size cannot be replicated with a font class)

2023-01-03 04:03 UTC, natashaannn commented on pages/innofest/index.tsx
> -                    <Image align="center" src={imageURL} height="100%" alt="" />
`<Image align="center" src={imageURL} width="100%" alt="" />`

Can you add this to map instead? Also you can [see this article](https://reactjs.org/docs/lists-and-keys.html) on how map works! ```map``` shouldn't affect performance, it is just a native javascript method and it is also best practice to use it!

2023-01-03 04:04 UTC, natashaannn requested changes
`map` shouldn't affect performance, so it'll be great if you could apply your change to the original map function!

2023-01-05 03:55 UTC, MakiseKurisuX commented on pages/innofest/index.tsx
> -                    <Image align="center" src={imageURL} height="100%" alt="" />
Fixed issue

2023-01-05 06:08 UTC, natashaannn approved these changes

2023-01-05 06:08 UTC, merged